# Type stubs for adsk.core module
from typing import Any, TypeVar

T = TypeVar('T')


class Product:
    """Base class for all Fusion products (Design, CAM, etc.)."""
    pass


class Application:
    @staticmethod
    def get() -> 'Application': ...
    @property
    def userInterface(self) -> 'UserInterface': ...
    @property
    def activeProduct(self) -> Product | None: ...
    def log(self, message: str, level: 'LogLevels', log_type: 'LogTypes') -> None: ...

class UserInterface:
    @property
    def commandDefinitions(self) -> 'CommandDefinitions': ...
    @property
    def workspaces(self) -> 'Workspaces': ...
    @property
    def activeSelections(self) -> 'Selections': ...
    def messageBox(self, message: str, title: str = ..., buttons: 'MessageBoxButtonTypes' = ..., icon: 'MessageBoxIconTypes' = ...) -> 'DialogResults': ...
    def inputBox(self, prompt: str, title: str = ..., defaultValue: str = ...) -> tuple[str, bool]: ...

class CommandDefinitions:
    def itemById(self, id: str) -> 'CommandDefinition | None': ...
    def addButtonDefinition(self, id: str, name: str, tooltip: str, resourceFolder: str = ...) -> 'CommandDefinition': ...

class CommandDefinition:
    @property
    def commandCreated(self) -> 'CommandCreatedEvent': ...
    def deleteMe(self) -> bool: ...

class Command:
    @property
    def commandInputs(self) -> 'CommandInputs': ...
    @property
    def execute(self) -> 'CommandEvent': ...
    @property
    def inputChanged(self) -> 'InputChangedEvent': ...
    @property
    def destroy(self) -> 'CommandEvent': ...
    @property
    def incomingFromHTML(self) -> 'HTMLEvent': ...
    @property
    def isOKButtonVisible(self) -> bool: ...
    @isOKButtonVisible.setter
    def isOKButtonVisible(self, value: bool) -> None: ...
    @property
    def okButtonText(self) -> str: ...
    @okButtonText.setter
    def okButtonText(self, value: str) -> None: ...
    def setDialogInitialSize(self, width: int, height: int) -> None: ...

class CommandInputs:
    def addDropDownCommandInput(self, id: str, name: str, style: 'DropDownStyles') -> 'DropDownCommandInput': ...
    def addStringValueInput(self, id: str, name: str, initialValue: str) -> 'StringValueCommandInput': ...
    def addValueInput(self, id: str, name: str, unitType: str, initialValue: 'ValueInput') -> 'ValueCommandInput': ...
    def addTextBoxCommandInput(self, id: str, name: str, text: str, numRows: int, isReadOnly: bool) -> 'TextBoxCommandInput': ...
    def addBoolValueInput(self, id: str, name: str, isCheckBox: bool, resourceFolder: str = ..., initialValue: bool = ...) -> 'BoolValueCommandInput': ...
    def addGroupCommandInput(self, id: str, name: str) -> 'GroupCommandInput': ...
    def addBrowserCommandInput(self, id: str, name: str, htmlFileURL: str, minimumHeight: int, maximumHeight: int = ...) -> 'BrowserCommandInput': ...
    def addRadioButtonGroupCommandInput(self, id: str, name: str) -> 'RadioButtonGroupCommandInput': ...
    def itemById(self, id: str) -> 'CommandInput | None': ...

class CommandInput:
    @property
    def id(self) -> str: ...
    @property
    def isVisible(self) -> bool: ...
    @isVisible.setter
    def isVisible(self, value: bool) -> None: ...

class GroupCommandInput(CommandInput):
    @property
    def children(self) -> CommandInputs: ...
    @property
    def isExpanded(self) -> bool: ...
    @isExpanded.setter
    def isExpanded(self, value: bool) -> None: ...

class DropDownCommandInput(CommandInput):
    @classmethod
    def cast(cls, obj: Any) -> 'DropDownCommandInput | None': ...
    @property
    def listItems(self) -> 'ListItems': ...
    @property
    def selectedItem(self) -> 'ListItem | None': ...

class StringValueCommandInput(CommandInput):
    @classmethod
    def cast(cls, obj: Any) -> 'StringValueCommandInput | None': ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...

class ValueCommandInput(CommandInput):
    @classmethod
    def cast(cls, obj: Any) -> 'ValueCommandInput | None': ...
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, value: float) -> None: ...
    @property
    def tooltip(self) -> str: ...
    @tooltip.setter
    def tooltip(self, value: str) -> None: ...
    @property
    def tooltipDescription(self) -> str: ...
    @tooltipDescription.setter
    def tooltipDescription(self, value: str) -> None: ...
    @property
    def isEnabled(self) -> bool: ...
    @isEnabled.setter
    def isEnabled(self, value: bool) -> None: ...

class TextBoxCommandInput(CommandInput):
    pass

class BoolValueCommandInput(CommandInput):
    @classmethod
    def cast(cls, obj: Any) -> 'BoolValueCommandInput | None': ...
    @property
    def value(self) -> bool: ...

class RadioButtonGroupCommandInput(CommandInput):
    @classmethod
    def cast(cls, obj: Any) -> 'RadioButtonGroupCommandInput | None': ...
    @property
    def listItems(self) -> 'ListItems': ...
    @property
    def selectedItem(self) -> 'ListItem | None': ...

class BrowserCommandInput(CommandInput):
    @classmethod
    def cast(cls, obj: Any) -> 'BrowserCommandInput | None': ...
    def sendInfoToHTML(self, action: str, data: str) -> str: ...
    @property
    def htmlFileURL(self) -> str: ...
    @htmlFileURL.setter
    def htmlFileURL(self, value: str) -> None: ...

class ListItems:
    @property
    def count(self) -> int: ...
    def add(self, name: str, isSelected: bool, icon: str = ..., index: int = ...) -> 'ListItem': ...
    def item(self, index: int) -> 'ListItem': ...

class ListItem:
    @property
    def name(self) -> str: ...
    @property
    def isSelected(self) -> bool: ...
    @isSelected.setter
    def isSelected(self, value: bool) -> None: ...
    def deleteMe(self) -> bool: ...

class ValueInput:
    @staticmethod
    def createByReal(value: float) -> 'ValueInput': ...

class Selections:
    @property
    def count(self) -> int: ...
    def item(self, index: int) -> 'Selection': ...

class Selection:
    @property
    def entity(self) -> Any: ...  # Dynamic type - cast to SketchLine, SketchArc, etc.

class Workspaces:
    def itemById(self, id: str) -> 'Workspace | None': ...

class Workspace:
    @property
    def toolbarTabs(self) -> 'ToolbarTabs': ...

class ToolbarTabs:
    def itemById(self, id: str) -> 'ToolbarTab | None': ...

class ToolbarTab:
    @property
    def toolbarPanels(self) -> 'ToolbarPanels': ...

class ToolbarPanels:
    def itemById(self, id: str) -> 'ToolbarPanel | None': ...
    def add(self, id: str, name: str, positionID: str, isBefore: bool) -> 'ToolbarPanel': ...

class ToolbarPanel:
    @property
    def controls(self) -> 'ToolbarControls': ...

class ToolbarControls:
    def itemById(self, id: str) -> 'ToolbarControl | None': ...
    def addCommand(self, commandDefinition: CommandDefinition) -> 'CommandControl': ...

class ToolbarControl:
    def deleteMe(self) -> bool: ...

class CommandControl(ToolbarControl):
    @property
    def isPromoted(self) -> bool: ...
    @isPromoted.setter
    def isPromoted(self, value: bool) -> None: ...

# Events
class Event:
    def add(self, handler: Any) -> None: ...  # Handler object with appropriate callback

class CommandCreatedEvent(Event):
    pass

class CommandEvent(Event):
    pass

class InputChangedEvent(Event):
    pass

class HTMLEvent(Event):
    pass

# Event Args - Base class for all event args
class EventArgs:
    """Base class for all Fusion event arguments."""
    pass

class CommandCreatedEventArgs(EventArgs):
    @property
    def command(self) -> Command: ...

class CommandEventArgs(EventArgs):
    @property
    def command(self) -> Command: ...

class InputChangedEventArgs(EventArgs):
    @property
    def input(self) -> CommandInput: ...
    @property
    def inputs(self) -> CommandInputs: ...

class HTMLEventArgs(EventArgs):
    @property
    def action(self) -> str: ...
    @property
    def data(self) -> str: ...
    @property
    def returnData(self) -> str: ...
    @returnData.setter
    def returnData(self, value: str) -> None: ...

# Enums
class DropDownStyles:
    TextListDropDownStyle: 'DropDownStyles'
    LabeledIconDropDownStyle: 'DropDownStyles'

class MessageBoxButtonTypes:
    OKButtonType: 'MessageBoxButtonTypes'
    YesNoButtonType: 'MessageBoxButtonTypes'

class MessageBoxIconTypes:
    InformationIconType: 'MessageBoxIconTypes'
    WarningIconType: 'MessageBoxIconTypes'

class DialogResults:
    DialogOK: 'DialogResults'
    DialogYes: 'DialogResults'
    DialogNo: 'DialogResults'

class LogLevels:
    InfoLogLevel: 'LogLevels'
    ErrorLogLevel: 'LogLevels'

class LogTypes:
    FileLogType: 'LogTypes'
    ConsoleLogType: 'LogTypes'
